#line 2 "scanner.cpp"

#line 4 "scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 69
#define YY_END_OF_BUFFER 70
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[289] =
    {   0,
       70,   68,   69,    1,   68,   69,   68,   69,   68,   69,
        4,   69,    1,    5,   69,    4,   69,    4,   69,    8,
       69,    6,    8,   69,    1,    7,   69,    8,   69,    8,
       69,   69,    1,   69,   69,   69,    1,    9,   68,   69,
       67,   68,   69,   51,   68,   69,   68,   69,   66,   68,
       69,   63,   68,   69,   68,   69,   42,   68,   69,   43,
       68,   69,   61,   68,   69,   59,   68,   69,   47,   68,
       69,   60,   68,   69,   68,   69,   62,   68,   69,   38,
       68,   69,   38,   68,   69,   44,   68,   69,   50,   68,
       69,   48,   68,   69,   49,   68,   69,   41,   68,   69,

       45,   68,   69,   46,   68,   69,   65,   68,   69,   41,
       68,   69,   41,   68,   69,   41,   68,   69,   41,   68,
       69,   41,   68,   69,   41,   68,   69,   41,   68,   69,
       41,   68,   69,   41,   68,   69,   41,   68,   69,   41,
       68,   69,   64,   68,   69,   52,   68,   69,    2,    3,
       67,   56,   40,   57,   38,   38,   35,   37,   38,   38,
       38,   54,   53,   55,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   21,   41,   26,   41,   41,
       41,   41,   41,   41,   28,   41,   41,   41,   58,   39,
       35,   36,   37,   38,   38,   38,   38,   34,   41,   41,

       41,   41,   41,   41,   41,   41,   41,   41,   25,   41,
       17,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   38,   34,   34,   34,   15,   41,   41,   31,   41,
       16,   41,   41,   41,   22,   41,   23,   41,   41,   41,
       18,   41,   41,   19,   41,   41,   41,   41,   41,   13,
       41,   41,   34,   34,   34,   34,   30,   41,   41,   41,
       14,   41,   41,   27,   41,   41,   41,   10,   41,   41,
       24,   41,   34,   41,   41,   11,   41,   33,   41,   12,
       41,   20,   41,   41,   32,   41,   29,   41
    } ;

static yyconst flex_int16_t yy_accept[231] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    4,    7,    9,   11,   13,   16,
       18,   20,   22,   25,   28,   30,   32,   33,   35,   36,
       37,   41,   44,   47,   49,   52,   55,   57,   60,   63,
       66,   69,   72,   75,   77,   80,   83,   86,   89,   92,
       95,   98,  101,  104,  107,  110,  113,  116,  119,  122,
      125,  128,  131,  134,  137,  140,  143,  146,  149,  149,
      150,  150,  151,  152,  153,  153,  154,  154,  155,  155,
      155,  155,  156,  157,  158,  159,  160,  161,  161,  162,
      163,  164,  165,  166,  167,  168,  169,  170,  171,  172,

      173,  174,  175,  176,  178,  180,  181,  182,  183,  184,
      185,  187,  188,  189,  190,  190,  190,  190,  190,  191,
      191,  191,  191,  191,  194,  195,  196,  197,  198,  199,
      200,  201,  202,  203,  204,  205,  206,  207,  208,  209,
      211,  213,  214,  215,  216,  217,  218,  219,  220,  221,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  223,
      224,  225,  226,  228,  229,  231,  233,  234,  235,  237,
      239,  240,  241,  243,  244,  246,  247,  248,  249,  250,
      252,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      254,  255,  256,  257,  259,  260,  261,  263,  264,  266,

      267,  268,  270,  271,  273,  273,  273,  273,  273,  274,
      275,  276,  278,  280,  282,  284,  284,  284,  284,  284,
      285,  287,  287,  287,  289,  289,  289,  289,  289,  289
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,    1,   23,
       24,   25,   26,   27,   28,   28,   28,   28,   28,   28,
       29,   29,   29,   29,   29,   30,   29,   29,   29,   29,
       29,   29,   29,   29,   31,   29,   29,   32,   29,   29,
       33,   34,   35,   36,   29,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   29,   46,   47,   29,   48,
       49,   29,   29,   50,   51,   52,   53,   54,   55,   32,
       29,   56,    1,   57,    1,   58,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[59] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    4,
        5,    1,    1,    1,    1,    2,    1,    5,    6,    6,
        7,    7,    1,    2,    1,    1,    4,    4,    5,    5,
        5,    4,    6,    6,    6,    6,    6,    7,    6,    7,
        6,    7,    7,    7,    6,    6,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[266] =
    {   0,
        0,    1,    2,    3,    9,   11,   12,   14,   17,   19,
       46,    0,  452,  453,  453,  448,  423,  453,  453,  446,
      421,  453,  453,  453,  444,  419,  453,  453,  442,  417,
      453,  439,  418,   99,  453,  432,  406,  453,  453,  453,
      453,  453,   14,   87,  453,  117,   92,  453,  415,  414,
      413,    0,  453,  453,  453,   65,   80,  395,  388,   81,
       68,  385,   84,   75,   82,  389,  375,  453,  428,  453,
      403,  453,  425,  453,  122,  453,  121,  453,  109,  131,
      138,    0,  148,  152,  156,  130,  150,    0,  135,  453,
      453,  453,    0,  379,  386,  375,  388,  376,  381,  136,

      375,  373,  370,    0,  367,  319,  318,  148,  305,  105,
        0,  307,  303,  453,  183,    0,    0,    0,  453,  186,
        0,    0,    0,  171,  155,  453,  260,  242,  163,  240,
      249,  244,  234,  231,  244,  238,  238,  227,  232,    0,
        0,  233,  229,  224,  217,  228,  218,  222,  225,  218,
      192,    0,  221,    0,  194,    0,  254,    0,  453,  191,
      177,  178,    0,  211,    0,    0,  211,  200,    0,    0,
      211,  199,    0,  207,    0,  197,  196,  187,  190,    0,
      196,  209,    0,    0,    0,  189,    0,    0,    0,  198,
      453,  206,  188,    0,  186,  186,    0,  188,    0,  171,

      112,    0,  103,    0,    0,    0,    0,    0,  453,   91,
       83,    0,    0,    0,    0,    0,  212,    0,  220,    1,
        0,    0,    0,    0,    0,    0,    0,    0,  453,  296,
      303,  310,  317,  324,  331,  338,  345,  349,  355,  361,
      365,  367,  369,  371,  373,  375,  377,  379,  381,  383,
      385,  387,  389,  391,  393,  395,  397,  399,  401,  403,
      405,  407,  409,  411,  413
    } ;

static yyconst flex_int16_t yy_def[266] =
    {   0,
      230,  230,  231,  231,  232,  232,  233,  233,  233,  233,
      229,   11,  229,  229,  229,  234,  235,  229,  229,  234,
      235,  229,  229,  229,  234,  235,  229,  229,  234,  235,
      229,  229,  229,  236,  229,  229,  237,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  238,  229,  229,  229,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  229,  229,  234,  229,
      235,  229,  229,  229,  236,  229,  239,  229,  237,  240,
      229,   46,  229,  229,  229,  229,  229,  241,  229,  229,
      229,  229,  238,  238,  238,  238,  238,  238,  238,  238,

      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  229,  236,  242,  243,  244,  229,  237,
      245,  246,  247,  229,  229,  229,  229,  229,  241,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      236,  248,  236,  249,  237,  250,  237,  251,  229,  229,
      229,  229,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  236,  252,  153,  253,  237,  254,  157,  255,  229,
      229,  229,  229,  238,  238,  238,  238,  238,  238,  238,

      238,  238,  238,  238,  256,  257,  258,  259,  229,  238,
      238,  238,  238,  238,  238,  260,  236,  261,  237,  238,
      238,  262,  263,  238,  264,  265,  257,  259,    0,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229
    } ;

static yyconst flex_uint16_t yy_nxt[512] =
    {   0,
      229,  229,   15,   15,   19,   19,   16,   16,   20,   20,
       23,   24,   23,   24,   28,   25,   28,   25,   29,   28,
       29,   28,  229,   29,  229,   29,   17,   17,   21,   21,
       81,  229,   82,   83,   83,   26,  229,   26,   30,  229,
       30,  224,  229,   30,  229,   30,   14,   14,   31,   32,
       33,   34,   16,   35,   36,   37,   38,   39,   40,   41,
       42,   43,   44,   45,   46,   47,   47,   48,   49,   50,
       51,   14,   17,   52,   52,   52,   52,   52,   53,   14,
       54,   55,   52,   56,   57,   58,   59,   60,   52,   52,
       61,   52,   62,   52,   52,   63,   64,   65,   52,   52,

       66,   52,   67,   68,   76,   84,   84,   84,   85,  104,
       83,   83,   83,   94,   95,  105,   96,  101,  119,  109,
      107,   86,   87,   97,  108,  102,  110,   76,   98,  103,
      111,  112,   77,   85,  221,   83,   83,   83,   89,  115,
      115,  147,   80,  220,   87,  215,   86,   87,   88,  120,
      120,  116,  117,  214,  148,   77,   84,   84,   84,  125,
      126,  121,  122,   89,   85,  126,   83,   83,   83,   87,
       84,   84,   84,  118,  124,  124,  124,   86,   87,  127,
      136,  125,  126,  123,  144,  126,  137,  126,   76,  124,
      124,  124,  160,  161,   89,  119,  128,   76,  119,  145,

       87,  151,  151,  119,  155,  155,  192,  126,  191,  162,
      182,  182,  186,  186,   76,  161,   77,   76,  213,   80,
      190,  191,   80,  193,  190,   77,   76,   80,  191,  119,
      191,  212,  211,  210,  209,  209,  204,  203,  202,  184,
      184,  184,   77,  191,  201,   77,  200,  199,  184,  198,
      191,  197,  196,   80,   77,  195,  194,  184,  184,  184,
      184,  184,  184,  119,  181,  180,  179,  178,  177,  176,
      175,  174,  188,  188,  188,  173,  172,  171,  170,  169,
      168,  188,  167,  166,  165,  164,  163,   80,  159,  159,
      188,  188,  188,  188,  188,  188,   14,   14,   14,   14,

       14,   14,   14,   18,   18,   18,   18,   18,   18,   18,
       22,   22,   22,   22,   22,   22,   22,   27,   27,   27,
       27,   27,   27,   27,   69,   69,   69,   69,   69,   69,
       69,   71,   71,   71,   71,   71,   71,   71,   75,   75,
       75,   75,   75,   75,   75,   79,   79,  150,   79,   79,
       79,   79,   93,   93,   93,   93,   75,   75,   75,  149,
      146,   75,   79,   79,   79,  143,  142,   79,  129,  129,
      152,  152,  153,  153,  154,  154,  156,  156,  157,  157,
      158,  158,  183,  183,  185,  185,  187,  187,  189,  189,
      205,  205,  206,  206,  207,  207,  208,  208,  216,  216,

      217,  217,  218,  218,  219,  219,  222,  222,  223,  223,
      225,  225,  226,  226,  227,  227,  228,  228,  141,  140,
      139,  138,  135,  134,  133,  132,  131,  130,   73,   72,
       70,  114,  113,  106,  100,   99,   92,   91,   90,   80,
       78,   74,   73,   72,   70,   72,   70,   72,   70,   72,
       70,  229,   13,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,

      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229
    } ;

static yyconst flex_int16_t yy_chk[512] =
    {   0,
        0,    0,    1,    2,    3,    4,    1,    2,    3,    4,
        5,    5,    6,    6,    7,    5,    8,    6,    7,    9,
        8,   10,    0,    9,    0,   10,    1,    2,    3,    4,
       43,    0,   43,   43,   43,    5,    0,    6,    7,    0,
        8,  220,    0,    9,    0,   10,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,

       11,   11,   11,   11,   34,   44,   44,   44,   47,   61,
       47,   47,   47,   56,   56,   61,   57,   60,   79,   64,
       63,   47,   47,   57,   63,   60,   64,   75,   57,   60,
       65,   65,   34,   46,  211,   46,   46,   46,   47,   77,
       77,  110,   79,  210,   47,  203,   46,   46,   46,   80,
       80,   77,   77,  201,  110,   75,   81,   81,   81,   86,
       86,   80,   80,   46,   83,   89,   83,   83,   83,   46,
       84,   84,   84,   77,   85,   85,   85,   83,   83,   87,
      100,   89,   86,   80,  108,  125,  100,   89,  115,  124,
      124,  124,  129,  129,   83,  120,   87,  151,  186,  108,

       83,  115,  115,  155,  120,  120,  161,  125,  162,  129,
      151,  151,  155,  155,  182,  129,  115,  217,  200,  120,
      160,  160,  186,  161,  162,  151,  153,  155,  190,  219,
      162,  198,  196,  195,  193,  192,  181,  179,  178,  153,
      153,  153,  182,  160,  177,  217,  176,  174,  153,  172,
      190,  171,  168,  219,  153,  167,  164,  153,  153,  153,
      153,  153,  153,  157,  150,  149,  148,  147,  146,  145,
      144,  143,  157,  157,  157,  142,  139,  138,  137,  136,
      135,  157,  134,  133,  132,  131,  130,  157,  128,  127,
      157,  157,  157,  157,  157,  157,  230,  230,  230,  230,

      230,  230,  230,  231,  231,  231,  231,  231,  231,  231,
      232,  232,  232,  232,  232,  232,  232,  233,  233,  233,
      233,  233,  233,  233,  234,  234,  234,  234,  234,  234,
      234,  235,  235,  235,  235,  235,  235,  235,  236,  236,
      236,  236,  236,  236,  236,  237,  237,  113,  237,  237,
      237,  237,  238,  238,  238,  238,  239,  239,  239,  112,
      109,  239,  240,  240,  240,  107,  106,  240,  241,  241,
      242,  242,  243,  243,  244,  244,  245,  245,  246,  246,
      247,  247,  248,  248,  249,  249,  250,  250,  251,  251,
      252,  252,  253,  253,  254,  254,  255,  255,  256,  256,

      257,  257,  258,  258,  259,  259,  260,  260,  261,  261,
      262,  262,  263,  263,  264,  264,  265,  265,  105,  103,
      102,  101,   99,   98,   97,   96,   95,   94,   73,   71,
       69,   67,   66,   62,   59,   58,   51,   50,   49,   37,
       36,   33,   32,   30,   29,   26,   25,   21,   20,   17,
       16,   13,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,

      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[70] =
    {   0,
1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0,     };

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Ascanner.l"
/*
Copyright (C) 2013 Lucas Beyer (http://lucasb.eyer.be)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to
deal in the Software without restriction, including without limitation the
rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
sell copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
IN THE SOFTWARE.
*/
#line 24 "Ascanner.l"
#include "debug_mode.h"

#define SAVE_TOKEN yylval.str = new std::string(yytext, yyleng)
#define TOKEN(t) (yylval.token = t)

#if TEST_MODE > TEST_SCANNER
#include "node.h"
#include "parser.hpp"

#define  SCAN(token) return TOKEN(token)
#define  _SCAN_STR(token_name)  do{ SAVE_TOKEN; return token_name; }while(0)

#else

#define  SCAN(token) printf("%s\n", #token)
#define  _SCAN_STR(token_name)  printf("%s:%s\n", #token_name, yytext)

#endif

#define  SCAN_CONST(token)	_SCAN_STR(CONST_##token)
#define  SCAN_ID()		_SCAN_STR(ID)
#define  SCAN_TRUE()		_SCAN_STR(TRUE)
#define  SCAN_FALSE()		_SCAN_STR(FALSE)

#include <cstring>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <stack>
#include <iostream>

/* globals to track current indentation */
int g_current_line_indent = 0;   /* indentation of the current line */
std::stack<size_t> g_indent_levels;
int g_is_fake_outdent_symbol = 0;

typedef struct _YYLTYPE {
	int first_column;
	int last_column;
	int first_line;
	int last_line;
} YYLTYPE;

YYLTYPE yylloc;

/* TODO: error-out on tabs/spaces mix? */
static const unsigned int TAB_WIDTH = 1;

/* Don't mangle yylex please! */
#define YY_DECL extern int yylex()
#define YYSTYPE int

#define YY_USER_INIT { \
        g_indent_levels.push(0); \
	yylloc.first_line = yylloc.first_column = 1; \
        BEGIN(initial); \
    }

int yycolumn = 1;
void set_yycolumn(int val) {
    yycolumn = val;
    yylloc.first_column = yycolumn;
    yylloc.last_column = yycolumn + yyleng - 1;
}

#define YY_USER_ACTION { \
    yylloc.first_line = yylloc.last_line = yylineno; \
    set_yycolumn(yycolumn); \
    yycolumn += yyleng; \
}

/* This is a sub-parser (state) for indentation-sensitive scoping */





/* %option 8bit reentrant bison-bridge */
/*%option debug*/
#line 833 "scanner.cpp"

#define INITIAL 0
#define initial 1
#define indent 2
#define ml_comment 3
#define sl_comment 4
#define normal 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 116 "Ascanner.l"

    int indent_caller = normal;
    int comment_caller = normal;

 /* This helps to keep track of the column number.
  * Note that it won't work if you have a rule which includes a newline and is
  * longer than one character because in that case that rule will be favored
  * and this one here won't get called.
  * TL;DR: If you have a rule which includes \n and more, you need to reset
  *        yycolumn inside that rule!
  */
#line 1074 "scanner.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 230 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 453 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
					{
					(yy_full_match) = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 127 "Ascanner.l"
{ set_yycolumn(0); yylineno--; REJECT; }
	YY_BREAK
case 2:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 128 "Ascanner.l"
{
#if TEST_MODE > TEST_SCANNER
#else
printf("SL_comment\n");
#endif
}
	YY_BREAK
/* "@"([^@]|\@+[^@])\@*"@" */
/* <normal>"@"([^@]|\@+[^@])*"@" */
/* "@"[^@]*"@"*/		/* @ Only recognize this as a comment @ */
/* ([@]+)([^@]*)([@]+) */	/* @@ Supports this as a comment @@@ */
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 138 "Ascanner.l"
{
#if TEST_MODE > TEST_SCANNER
#else
printf("ML_comment\n");
#endif
}
	YY_BREAK
/* Everything runs in the <normal> mode and enters the <indent> mode
    when a newline symbol is encountered.
    There is no newline symbol before the first line, so we need to go
    into the <indent> mode by hand there.
 */
case 4:
YY_RULE_SETUP
#line 150 "Ascanner.l"
{ set_yycolumn(yycolumn-1); indent_caller = normal; yyless(0); BEGIN(indent); }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 151 "Ascanner.l"
{ indent_caller = normal; yyless(0); BEGIN(indent); }
	YY_BREAK
/* The following are the rules that keep track of indentation. */
case 6:
YY_RULE_SETUP
#line 154 "Ascanner.l"
{ g_current_line_indent = (g_current_line_indent + TAB_WIDTH) & ~(TAB_WIDTH-1); }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 155 "Ascanner.l"
{ g_current_line_indent = 0; /* ignoring blank line */ }
	YY_BREAK
case YY_STATE_EOF(indent):
#line 156 "Ascanner.l"
{
                    // When encountering the end of file, we want to emit an
                    // outdent for all indents currently left.
                    if(g_indent_levels.top() != 0) {
                        g_indent_levels.pop();

                        // See the same code below (<indent>.) for a rationale.
                        if(g_current_line_indent != g_indent_levels.top()) {
                            unput('\n');
                            for(size_t i = 0 ; i < g_indent_levels.top() ; ++i) {
                                unput('\t');
                            }
                        } else {
                            BEGIN(indent_caller);
                        }
			
			SCAN(UNINDENT);
			
                    } else {
                        yyterminate();
                    }
                }
	YY_BREAK
/* <indent>"#".*$  {
#if TEST_MODE > TEST_SCANNER
#else
printf("indent_SL_comment\n");
#endif
} */
case 8:
YY_RULE_SETUP
#line 185 "Ascanner.l"
{
                    if(!g_is_fake_outdent_symbol) {
                        unput(*yytext);
                    }
                    set_yycolumn(yycolumn-1);
                    g_is_fake_outdent_symbol = 0;

                    // Indentation level has increased. It can only ever
                    // increase by one level at a time. Remember how many
                    // spaces this level has and emit an indentation token.
                    if(g_current_line_indent > g_indent_levels.top()) {
                        g_indent_levels.push(g_current_line_indent);
                        BEGIN(indent_caller);
			
			SCAN(INDENT);

                    } else if(g_current_line_indent < g_indent_levels.top()) {
                        // Outdenting is the most difficult, as we might need to
                        // outdent multiple times at once, but flex doesn't allow
                        // emitting multiple tokens at once! So we fake this by
                        // 'unput'ting fake lines which will give us the next
                        // outdent.
                        g_indent_levels.pop();

                        if(g_current_line_indent != g_indent_levels.top()) {
                            // Unput the rest of the current line, including the newline.
                            // We want to keep it untouched.
                            for(size_t i = 0 ; i < g_current_line_indent ; ++i) {
                                unput('\t');
                            }
                            unput('\n');
                            // Now, insert a fake character indented just so
                            // that we get a correct outdent the next time.
                            unput('.');
                            // Though we need to remember that it's a fake one
                            // so we can ignore the symbol.
                            g_is_fake_outdent_symbol = 1;
                            for(size_t i = 0 ; i < g_indent_levels.top() ; ++i) {
                                unput('\t');
                            }
                            unput('\n');
                        } else {
                            BEGIN(indent_caller);
                        }

			SCAN(UNINDENT);

                    } else {
                        // No change in indentation, not much to do here...
                        BEGIN(indent_caller);
                    }
                }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 238 "Ascanner.l"
{ g_current_line_indent = 0; indent_caller = YY_START; BEGIN(indent); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 240 "Ascanner.l"
{SCAN(START);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 241 "Ascanner.l"
{SCAN(FINISH);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 244 "Ascanner.l"
{SCAN(SIZEOF);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 246 "Ascanner.l"
{SCAN_TRUE();}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 247 "Ascanner.l"
{SCAN_FALSE();}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 249 "Ascanner.l"
{SCAN(BOOL);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 250 "Ascanner.l"
{SCAN(CHAR);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 251 "Ascanner.l"
{SCAN(INT);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 252 "Ascanner.l"
{SCAN(LONG);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 253 "Ascanner.l"
{SCAN(REAL);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 254 "Ascanner.l"
{SCAN(STRING);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 256 "Ascanner.l"
{SCAN(IF);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 257 "Ascanner.l"
{SCAN(ELIF);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 258 "Ascanner.l"
{SCAN(ELSE);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 260 "Ascanner.l"
{SCAN(WHILE);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 261 "Ascanner.l"
{SCAN(FOR);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 262 "Ascanner.l"
{SCAN(IN);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 263 "Ascanner.l"
{SCAN(RANGE);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 264 "Ascanner.l"
{SCAN(TO);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 266 "Ascanner.l"
{SCAN(CONTINUE);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 267 "Ascanner.l"
{SCAN(BREAK);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 268 "Ascanner.l"
{SCAN(CASE);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 269 "Ascanner.l"
{SCAN(DEFAULT);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 271 "Ascanner.l"
{SCAN(RETURN);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 274 "Ascanner.l"
{SCAN_CONST(INT);}
	YY_BREAK
/*
{	yylval.intval = strtol(yytext,NULL,0);
	printf("hex int const\n");
	//return(CONST_INT);
}
 */
case 35:
YY_RULE_SETUP
#line 281 "Ascanner.l"
{SCAN_CONST(REAL);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 282 "Ascanner.l"
{SCAN_CONST(REAL);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 283 "Ascanner.l"
{SCAN_CONST(REAL);}
	YY_BREAK
/*
<normal>[-]?[0-9]*\.[0-9]*		{SCAN_CONST(REAL);}
 */
/*
{
	yylval.rval = atof(yytext);
	printf("float const\n");
	//return(CONST_REAL);
}
 */
case 38:
YY_RULE_SETUP
#line 294 "Ascanner.l"
{SCAN_CONST(INT);} 
	YY_BREAK
/*
<normal>[-]?[1-9][0-9]*{ILEN}?		{SCAN_CONST(INT);}
<normal>[-]?[0]*{ILEN}?			{SCAN_CONST(INT);}
 */
/*
{
	yylval.intval = atoi(yytext);
	printf("int const\n");
	//return(CONST_INT);
}
 */
/*[-]?0[0-7]*{ILEN}?		{SCAN_CONST(INT);}*/
/*
{
	yylval.intval = strtol(yytext,NULL,8);
	printf("oct int const\n");
	//return(CONST_INT);
}
 */
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 316 "Ascanner.l"
{SCAN_CONST(CHAR);}
	YY_BREAK
/*
{
	char c[2];
	substring(yytext,c,2,1);
	yylval.cval = c[0];
	printf("character const\n");
	//return(CONST_CHAR);
}
 */
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 327 "Ascanner.l"
{SCAN_CONST(STRING);}
	YY_BREAK
/*
{
	int len = strlen(yytext);
	substring(yytext, yylval.sval, 2, len-2);
	//yylval.id = (char*) strdup(yytext);
	printf("string const\n");
	//return(CONST_STRING);
}
 */
case 41:
YY_RULE_SETUP
#line 338 "Ascanner.l"
{SCAN_ID();}
	YY_BREAK
/*
{
	printf("%s", yytext);
	yylval.id = (char*) strdup(yytext);
	//return(ID);
}
 */
/*
<normal>"#".*$ {
#if TEST_MODE > TEST_SCANNER
#else
printf("SL_comment\n");
#endif
}
 */
/* "@"([^@]|\@+[^@])\@*"@" */
/* <normal>"@"([^@]|\@+[^@])*"@" */
/* "@"[^@]*"@" */		/* @ Only recognize this as a comment @ */
/* ([@]+)([^@]*)([@]+) */	/* @@ Supports this as a comment @@@ */
/*
<normal>([@]+)([^@]*)([@]+) {
#if TEST_MODE > TEST_SCANNER
#else
printf("ML_comment\n");
#endif
}
 */
/*
<normal>[@]+ {
BEGIN(ml_comment);
#if TEST_MODE > TEST_SCANNER
#else
printf("ML_comment_Start\n");
#endif
}
<ml_comment>"@" {
BEGIN(normal);
#if TEST_MODE > TEST_SCANNER
#else
printf("ML_comment_End\n");
#endif
} //"#".*\n	{printf("SL_comment\n");}
<ml_comment>. {}
 */
/* separators */
case 42:
YY_RULE_SETUP
#line 384 "Ascanner.l"
{ SCAN(LPAREN);}//return(LPAREN); 
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 385 "Ascanner.l"
{ SCAN(RPAREN);}//return(RPAREN); 
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 386 "Ascanner.l"
{ SCAN(COLON);}//return(COLON);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 387 "Ascanner.l"
{ SCAN(LBRACK);}//return(LBRACK);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 388 "Ascanner.l"
{ SCAN(RBRACK);}//return(RBRACK); 
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 389 "Ascanner.l"
{ SCAN(COMMA);}//return(COMMA); 
	YY_BREAK
/* operators */
case 48:
YY_RULE_SETUP
#line 394 "Ascanner.l"
{ SCAN(EQ);}//return(EQ); 
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 395 "Ascanner.l"
{ SCAN(GT);}//return(GT); 
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 396 "Ascanner.l"
{ SCAN(LT);}//return(LT); 
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 397 "Ascanner.l"
{ SCAN(NOT);}//return(NOT); 
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 398 "Ascanner.l"
{ SCAN(COMP);}//return(COMP);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 399 "Ascanner.l"
{ SCAN(EQEQ);}//return(EQEQ); 
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 400 "Ascanner.l"
{ SCAN(LTEQ);}//return(LTEQ); 
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 401 "Ascanner.l"
{ SCAN(GTEQ);}//return(GTEQ); 
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 402 "Ascanner.l"
{ SCAN(NOTEQ);}//return(NOTEQ); 
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 403 "Ascanner.l"
{ SCAN(ANDAND);}//return(ANDAND); 
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 404 "Ascanner.l"
{ SCAN(OROR);}//return(OROR);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 405 "Ascanner.l"
{ SCAN(PLUS);}//return(PLUS); 
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 406 "Ascanner.l"
{ SCAN(MINUS);}//return(MINUS); 
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 407 "Ascanner.l"
{ SCAN(MULT);}//return(MULT); 
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 408 "Ascanner.l"
{ SCAN(DIV);}//return(DIV); 
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 409 "Ascanner.l"
{ SCAN(AND);}//return(AND);
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 410 "Ascanner.l"
{ SCAN(OR); }//return(OR); 
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 411 "Ascanner.l"
{ SCAN(XOR);}//return(); 
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 412 "Ascanner.l"
{ SCAN(MOD);}//; 
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 414 "Ascanner.l"
//{ printf("kossher\n"); } //return TOK_REST;
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 415 "Ascanner.l"
//{ std::cerr << __FILE__ << ":" << yylineno << ":" << yycolumn << ": Unexpected character: " << yytext << std::endl; exit(1); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 417 "Ascanner.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1701 "scanner.cpp"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(initial):
			case YY_STATE_EOF(ml_comment):
			case YY_STATE_EOF(sl_comment):
			case YY_STATE_EOF(normal):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 230 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 230 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 229);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; // After all that talk, this was set to 1 anyways...
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 417 "Ascanner.l"


#if TEST_MODE == TEST_SCANNER
int main(int argc, char* argv[]) {
printf("from main:\n");
  yylex() ;
  printf("\n") ;
}
#endif

